# https://travis-ci.org/#!/translate/amagama
language: python
python:
  - 2.6
  - 2.7
  - 3.3
matrix:
  allow_failures:
    - python: 3.3
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install --upgrade git+https://github.com/translate/translate.git; fi
  - pip install -r requirements/dev.txt
before_script:
  - export PATH=`pwd`/bin:$PATH
  - export PYTHONPATH=`pwd``python -c 'import os, sys; print(os.pathsep.join(sys.path))'`
  - psql -c "CREATE DATABASE amagama WITH ENCODING 'UTF-8';" -U postgres
script:
  - python -m compileall -q -f .
  - make docs
  - amagama-manage initdb -s en
  - amagama-manage tmdb_stats
  - yes | amagama-manage dropdb -s en
  - pep8.sh travis
notifications:
  email:
    on_failure: always
    on_success: change
